export default [
  "You can't generate the driver without transmitting the open-source COM monitor!",
  'Try to synthesize the FTP bus, maybe it will compress the 1080p program!',
  'We need to back up the online JSON bus!',
  "You can't synthesize the port without synthesizing the optical SDD capacitor!",
  'We need to navigate the open-source AGP alarm!',
  "You can't override the hard drive without backing up the auxiliary CSS hard drive!",
  'Try to calculate the PNG monitor, maybe it will synthesize the open-source sensor!',
  "You can't compress the system without copying the back-end GB feed!",
  "You can't index the array without synthesizing the cross-platform FTP microchip!",
  'The JSON alarm is down, synthesize the redundant matrix so we can navigate the RAM interface!',
  'Use the auxiliary FTP transmitter, then you can quantify the virtual feed!',
  "synthesizing the alarm won't do anything, we need to index the mobile SMS capacitor!",
  "I'll connect the open-source SMTP array, that should alarm the GB panel!",
  "I'll parse the multi-byte ADP hard drive, that should driver the JSON firewall!",
  "You can't copy the driver without navigating the neural USB interface!",
  'Use the neural SCSI driver, then you can navigate the multi-byte pixel!',
  "copying the bus won't do anything, we need to quantify the primary GB microchip!",
  'The USB capacitor is down, quantify the mobile application so we can bypass the COM feed!',
  'The SCSI monitor is down, override the auxiliary panel so we can calculate the PCI monitor!',
  'We need to hack the solid state TCP capacitor!',
  "You can't compress the bandwidth without backing up the optical SCSI array!",
  "copying the monitor won't do anything, we need to reboot the open-source JSON matrix!",
  'If we compress the matrix, we can get to the HDD sensor through the bluetooth SQL circuit!',
  "You can't copy the array without parsing the digital AGP capacitor!",
  "You can't index the program without bypassing the wireless XSS system!",
  "You can't reboot the circuit without hacking the mobile SQL alarm!",
  'Use the mobile SQL circuit, then you can override the auxiliary monitor!',
  "programming the protocol won't do anything, we need to hack the bluetooth JSON firewall!",
  'Try to navigate the SMTP feed, maybe it will calculate the open-source panel!',
  'The AGP pixel is down, reboot the virtual system so we can navigate the SSL system!',
  'We need to override the neural CSS pixel!',
  "You can't connect the alarm without programming the primary IB transmitter!",
  'Use the wireless HDD feed, then you can back up the mobile interface!',
  "I'll parse the 1080p IB panel, that should array the IB application!",
  'The COM pixel is down, index the neural panel so we can copy the PNG interface!',
  "I'll reboot the redundant JBOD capacitor, that should panel the USB program!",
  "I'll connect the optical COM driver, that should alarm the SMS bus!",
  "I'll index the mobile THX capacitor, that should feed the TCP alarm!",
  'Use the online JBOD matrix, then you can parse the primary array!',
  'If we index the firewall, we can get to the SSL application through the mobile RSS panel!',
  "parsing the monitor won't do anything, we need to calculate the bluetooth AGP matrix!",
  'We need to program the multi-byte SMTP bus!',
  "synthesizing the card won't do anything, we need to calculate the haptic USB bus!",
  "I'll compress the optical COM monitor, that should transmitter the SDD feed!",
  "I'll quantify the 1080p PNG interface, that should card the XML bus!",
  'Try to generate the XSS hard drive, maybe it will input the 1080p hard drive!',
  'Try to compress the JSON hard drive, maybe it will generate the neural port!',
  "bypassing the bus won't do anything, we need to compress the primary SMS bandwidth!",
  'The ADP capacitor is down, compress the cross-platform transmitter so we can quantify the TCP capacitor!',
  'Use the 1080p TCP capacitor, then you can index the primary system!',
  'The SQL program is down, index the neural hard drive so we can navigate the SMTP protocol!',
  'The RAM application is down, reboot the bluetooth program so we can bypass the SCSI program!',
  "I'll calculate the cross-platform USB interface, that should matrix the SDD alarm!",
  "You can't calculate the bus without parsing the open-source SQL feed!",
  'We need to index the digital IB panel!',
  "You can't index the array without bypassing the virtual XSS system!",
  "programming the feed won't do anything, we need to back up the mobile PCI port!",
  "compressing the matrix won't do anything, we need to generate the redundant XML panel!",
  'Try to calculate the IB bus, maybe it will quantify the online array!',
  "You can't program the firewall without navigating the digital COM protocol!",
  'The PNG card is down, generate the wireless matrix so we can back up the JBOD microchip!',
  'If we navigate the pixel, we can get to the HDD interface through the wireless SSL array!',
  'We need to quantify the redundant XSS system!',
  "connecting the application won't do anything, we need to index the multi-byte JSON firewall!",
  "calculating the capacitor won't do anything, we need to parse the auxiliary JBOD bus!",
  'Try to index the RAM circuit, maybe it will compress the back-end protocol!',
  'We need to program the digital SMTP transmitter!',
  "hacking the driver won't do anything, we need to synthesize the wireless CSS sensor!",
  'Use the primary SQL port, then you can parse the bluetooth monitor!',
  'Try to copy the GB application, maybe it will compress the mobile transmitter!',
  'The SMS hard drive is down, reboot the solid state driver so we can quantify the XML hard drive!',
  'We need to copy the neural GB application!',
  'The GB feed is down, index the bluetooth interface so we can copy the COM program!',
  'Try to program the EXE application, maybe it will program the solid state pixel!',
  'We need to parse the auxiliary SQL array!',
  'Try to compress the RSS bus, maybe it will compress the optical panel!',
  'The GB bandwidth is down, override the 1080p card so we can connect the GB application!',
  'If we hack the pixel, we can get to the CSS sensor through the back-end RSS circuit!',
  "I'll program the online COM system, that should matrix the GB application!",
  "You can't program the program without parsing the redundant COM port!",
  'Try to input the JSON circuit, maybe it will parse the optical matrix!',
  'If we copy the system, we can get to the SAS pixel through the neural SDD capacitor!',
  "I'll generate the digital HTTP circuit, that should circuit the SMS hard drive!",
  'If we synthesize the capacitor, we can get to the RAM array through the digital PNG port!',
  "hacking the protocol won't do anything, we need to generate the primary EXE panel!",
  'The JSON circuit is down, calculate the back-end alarm so we can program the IB alarm!',
  'If we transmit the panel, we can get to the IB protocol through the redundant CSS bandwidth!',
  "I'll quantify the multi-byte PNG transmitter, that should protocol the AGP pixel!",
  "synthesizing the driver won't do anything, we need to copy the bluetooth FTP array!",
  "You can't reboot the transmitter without programming the cross-platform JBOD capacitor!",
  'Use the multi-byte THX bus, then you can reboot the digital hard drive!',
  'Try to hack the SSL system, maybe it will hack the primary monitor!',
  'We need to parse the haptic PNG array!',
  'If we navigate the application, we can get to the GB card through the digital THX port!',
  "You can't navigate the interface without parsing the primary SCSI system!",
  "compressing the bandwidth won't do anything, we need to synthesize the redundant AGP firewall!",
  "synthesizing the array won't do anything, we need to copy the cross-platform PCI transmitter!",
  "You can't transmit the system without parsing the auxiliary TCP interface!",
  'Try to bypass the THX system, maybe it will transmit the online interface!',
  'The XSS sensor is down, synthesize the open-source monitor so we can connect the USB port!'
];
