export const randomCrimeString = [
  "Selling fake nudes for bitcoins with deepfake",
  "Using your webdev skills to create a fake Paypal website.",
  "Claiming to be a nigerian prince, and sends out a bunch of emails using advanced scripts...",
  "Asking your facebook friends for their password.",
  "Impersonate as the perfect girl on Tinder, asking guys for funds.",
  "Tricking eldery people to give their credit card information.",
  "Attaching keylogger malware to your emails.",
  "Setting up a fake fundraiser, and asks grandmother to chip in a little extra",
  "Trying to log in to others bank account by trial and error.",
  "Setting up a bitcoin-mining-app in the background of your text-based MMORPG...",
  "Shutting down Irans nuclear program.",
  "Fetching personal data from Ashley Madison dating website.",
  "Observing Home Depots trancsaction through the US...",
  "Rebooting the Melissa Virus... It is super effective!",
  "Breaking into Sony Playstation... Greeted by a lot of japanese people. This is nice..",
  "Stealing login credentials to Mt. Gox Bitcoin exchange...",
  "Spreading Wannacry ransomware... Login: Wanna_cry, Password: ran_some_where. Access granted!",
  "Stealing personal information from Equifax...",
  "Breaking into Pentagon and selling their software on ebay",
  "Trading Chartreuse on the black market: A shady guy named mc100s is willing to sell it!",
  "Putting on a hoodie and skimask and punches keyboard furiously.",
  "Setting up local printer in order to print out cash you just stole from the interwebz.",
  "Changing the theme on your terminal to neon-green in order to be more effective.",
  "Installing bcrypt on enemy computer in order to mess him up for life.",
  "Accessing files... struct ip_config_file_uploader = function(password) {console.log(debug_report); return ip}...",
  "setting up listener to external api-point by Overtaking Justice Under New Alias",
  "Rehosting server to accesspoint... Function denied, relocating host point to ip...",
  "Ip config. 15.345.1.508 annihilating system software extras and extracting new data to disc. Reallocating new Malware to system disc.",
  "Typescript system activated and transferred to new directory encrypted with an IBAN number of 19029839.",
  "Console logging that sucker to see if there is an end_result: var type_in_user = {aku += 10} to user: 'Some_basement_guy'. Response awaiting...",
  "Searching the depths of web to solve an algorithm by applying the known map, filter => reduce technique.",
  "Deploying repository and git commit -m 'Advanced Update': Functioning: 1002.10002. 333 updated!",
  "Userinterface activated by struct ip_hbs_active = resolution => return array[1223, 9532, 2846]. Looking for new updates to system-ware and hiking.",
  "Constructing a VPN to server: 100%, connecting through active_flow_chart123 and deploying mechanism... Active and responsive!",
  "Advanced css => upload ??? and activating decomposition to resolve Promise sent by FBI.",
  "Git push origin_encrypted_secret master. Activating git pull request... Waiting for server to respond... Access granted on specific terms",
  "Origin base requested from server: 1.119.1337.923. Accepted!",
  "101010111010100011111010010010010101010101010101001011 0101011010101010101001010111010101010010101001100",
  "Running around the house trying to find the battery charger, but it failed to commit... System reboots: external_battery_source = True",
  "Installing PassportJS on enemy computer in order to confuse him for a life time.... ",
  "let i = 0; while (i <=10) { document.write('your browser is about to crash<br />);} ",
  "Setting Internet Explorer 6 as default browser on enemy computer "
];

export const errorMessages = [
  "Uncaught TypeError: Cannot read property",
  "TypeError: ‘undefined’ is not an object (evaluating)",
  "TypeError: null is not an object (evaluating)",
  "(unknown): Script error",
  "TypeError: ‘undefined’ is not a function",
  "Uncaught RangeError: Maximum call stack",
  "404 not found",
  "403 forbidden",
  "500 internal server error",
  "503 Service Unavailable",
  "504 Gateway Timeout",
  "0x80070057, WindowsUpdate_8007002C, WindowsUpdate_dt000",
  "Runtime Error",
  "Improper Input Validation",
  "Improper Encoding or Escaping of Output",
  "Failure to Preserve SQL Query Structure",
  "Failure to Preserve Web Page Structure",
  "Failure to Preserve OS Command Structure",
  "EXT2-fs: warning: mounting unchecked file system",
  "cannot open shared object file: No such file or directory"
];

export default {
  randomCrimeString,
  errorMessages
};
